os:
  - Visual Studio 2013

install:
  - third\bx\tools\bin\windows\genie --file=scripts\genie.lua --with-luajit --with-openal --with-bullet --with-tools vs2013

platform:
  - Win32
  - x64

configuration:
  - debug
  - development
  - release

build:
  project: build/engine/projects/vs2013/crown.sln
