os:
  - Visual Studio 2013

install:
  - third\bx\tools\bin\windows\genie --file=genie\genie.lua --with-luajit --with-openal --with-bullet --with-tools vs2013

platform:
  - Win32
  - x64

configuration:
  - debug
  - development
  - release

test_script:
  - build/win32/bin/crown-debug-32 --run-unit-tests
  - build/win32/bin/crown-development-32 --run-unit-tests
  - build/win64/bin/crown-debug-64 --run-unit-tests
  - build/win64/bin/crown-development-64 --run-unit-tests

build:
  project: build/projects/vs2013/crown.sln
