sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:vala-team -y
  - sudo apt-get -qq update
  - sudo apt-get install -y libmesa-dev
  - sudo apt-get install -y libpulse-dev
  - sudo apt-get install -y libxrandr-dev

script:
  - make linux-debug64       && ./build/linux64/bin/crown-debug --run-unit-tests
  - make linux-development64 && ./build/linux64/bin/crown-development --run-unit-tests
  - make linux-release64     && ./build/linux64/bin/crown-release --run-unit-tests

notifications:
  email: false
